### ISSUE TITLE
Day 12:vim-surround 文档错误：删除包裹的符号，命令错误

### ISSUE THREAD

**Issue by itchaox** [Nauxscript/Just-Vim-It#3]
地址：Day 12:vim-surround 文档错误：删除包裹的符号，命令错误
具体位置：
![image](https://user-images.githubusercontent.com/81410510/206364991-ed5ba477-558e-4894-beb2-485419cfc38a.png)

itchao
2022年12月8日13:35:00

**Comment by Nauxscript** [comment]
好的 过两天改一下 这两天阳了太难受了，或者直接提个pr就更好了😁
