### ISSUE TITLE
你好，请教一下，你的这些 day-45.md 这样的目录是手动写的还是自动生成的侧边栏，谢谢

### ISSUE THREAD

**Issue by itchaox** [Nauxscript/Just-Vim-It#30]

**Comment by Nauxscript** [comment]
https://github.com/Nauxscript/Just-Vim-It/blob/5ba52bcd2127e685f78a542e6576ef80c6486143/docs/.vitepress/config.js#L240

在这个配置文件中设置的，你看看

**Comment by itchaox** [comment]
> https://github.com/Nauxscript/Just-Vim-It/blob/5ba52bcd2127e685f78a542e6576ef80c6486143/docs/.vitepress/config.js#L240
> 
> 在这个配置文件中设置的，你看看

你好，我的意思是你的这个映射关系是自己手动写的，还是有什么插件自动生成的吗？
  items: [{
            text: 'Day 1：起步',
            link: '/vim/day-1.md'
          },
          {
            text: 'Day 2：行相关命令',
            link: '/vim/day-2.md'
          },
          {
            text: 'Day 3：认识 vim 语法',
            link: '/vim/day-3.md'
          },
          {
            text: 'Day 4：删改重做命令提升效率',
            link: '/vim/day-4.md'
          },
          {
            text: 'Day 5：认识可视化模式',
            link: '/vim/day-5.md'
          },
          {
            text: 'Day 6：什么是文本对象？',
            link: '/vim/day-6.md'
          },
          {
            text: 'Day 7：让移动再次快起来!',
            link: '/vim/day-7.md'
          },

**Comment by Nauxscript** [comment]
oh，这个是自己添加的，请参考 [vitepress 文档：default-theme-sidebar](https://vitepress.dev/reference/default-theme-sidebar)

**Comment by itchaox** [comment]
> oh，这个是自己添加的，请参考 [vitepress 文档：default-theme-sidebar](https://vitepress.dev/reference/default-theme-sidebar)

了解了，谢谢你
